version: "3"

services:
    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
            - MYSQL_DATABASE=wordpress
        volumes:
            - dbdata:/var/lib/mysql
        command: "--default-authentication-plugin=mysql_native_password"
        networks:
            - app-network

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
        networks:
            - app-network

    wordpress-service:
        depends_on:
            - db
        image: wordpress
        container_name: wordpress
        restart: unless-stopped
        env_file: .env
        ports:
            - 8081:80
        environment:
            - WORDPRESS_DB_HOST=db:3306
            - WORDPRESS_DB_USER=$MYSQL_USER
            - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
            - WORDPRESS_DB_NAME=wordpress
        volumes:
            - wordpress:/var/www/html
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: docker-next
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - appdata:/app/node_modules
        networks:
            - app-network

    webserver:
        depends_on:
            - wordpress-service
            - app
        image: nginx:1.15.12-alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "3345:80"
        volumes:
            - wordpress:/var/www/html
            - ./nginx-conf:/etc/nginx/conf.d
        networks:
            - app-network

volumes:
    wordpress:
    dbdata:
    appdata:

networks:
    app-network:
        driver: bridge
